const data = [
  {
    id: 1,
    name: "ElectricCar1",
    img: "../../../imgs/Electric Car 1.jpg",
    topSpeed: 125,
    batteryCapacity: 75.5,
    efficiency: 260,
    horsePower: 400,
    range: 300,
    chargeTime: 8,
  },
  {
    id: 2,
    name: "ElectricCar2",
    img: "../../../imgs/Electric Car 2.jpg",
    topSpeed: 120,
    batteryCapacity: 70.5,
    efficiency: 260,
    horsePower: 400,
    range: 300,
    chargeTime: 8,
  },
  {
    id: 3,
    name: "ElectricCar3",
    img: "../../../imgs/Electric Car 3.jpg",
    topSpeed: 140,
    batteryCapacity: 90.5,
    efficiency: 260,
    horsePower: 400,
    range: 300,
    chargeTime: 8,
  },
  {
    id: 4,
    name: "ElectricMotorbike1",
    img: "../../../imgs/Electric Motorbike 1.jpg",
    topSpeed: 90,
    batteryCapacity: 40,
    efficiency: 100,
    horsePower: 80,
    range: 100,
    chargeTime: 6,
  },
  {
    id: 5,
    name: "ElectricMotorbike2",
    img: "../../../imgs/Electric Motorbike 2.jpg",
    topSpeed: 80,
    batteryCapacity: 35,
    efficiency: 75,
    horsePower: 80,
    range: 100,
    chargeTime: 6,
  },
  {
    id: 6,
    name: "ElectricMotorbike3",
    img: "../../../imgs/Electric Motorbike 3.jpg",
    topSpeed: 95,
    batteryCapacity: 45,
    efficiency: 120,
    horsePower: 80,
    range: 100,
    chargeTime: 6,
  },
  {
    id: 7,
    name: "ElectricTractor1",
    img: "../../../imgs/Electric Tractor 1.jpg",
    topSpeed: 65,
    batteryCapacity: 65,
    efficiency: 75,
    horsePower: 40,
    range: 100,
    chargeTime: 15,
  },
  {
    id: 8,
    name: "ElectricTractor2",
    img: "../../../imgs/Electric Tractor 2.jpg",
    topSpeed: 50,
    batteryCapacity: 45,
    efficiency: 60,
    horsePower: 40,
    range: 100,
    chargeTime: 15,
  },
  {
    id: 9,
    name: "ElectricTractor3",
    img: "../../../imgs/Electric Tractor 3.jpg",
    topSpeed: 60,
    batteryCapacity: 60,
    efficiency: 70,
    horsePower: 40,
    range: 100,
    chargeTime: 15,
  },
];

export default data;
